index.html: Add github icon and change footer address
fossasia/fossasia.org pull request #175
Opened 2017-09-17 12:03 UTC by sagar-kalra

Add github icon in the menu bar and change Footer address

Fixes https://github.com/fossasia/fossasia.org/issues/168

2017-09-17 14:53 UTC, mariobehling commented
Thanks! Please provide a screenshot and test page.

2017-09-18 06:15 UTC, sagar-kalra commented
Here is the test link :- https://sagar-kalra.github.io/fossasia.org/
![screenshot from 2017-09-18 11-45-01](https://user-images.githubusercontent.com/31239108/30530727-c04dad40-9c38-11e7-8fc6-7cfd5f0fdf80.png)

2017-09-18 06:40 UTC, mariobehling commented
Why is there a reference to a Jekyll theme? Don't add "FOSSASIA" twice. I am unclear what you are trying to do.

2017-09-18 08:04 UTC, sagar-kalra commented
I ll correct it. Sorry, for the mistake.

2017-09-18 09:58 UTC, mariobehling commented
Github icon not aligned and in the same size as other icons.

![screenshot from 2017-09-18 11-57-39](https://user-images.githubusercontent.com/1583873/30537084-a9fd167c-9c68-11e7-95f6-5052bc9bd323.png)

2017-09-18 16:59 UTC, sagar-kalra commented
i changed everything you asked. I also increased the size of github icon, but i am unsuccessful in positioning it as same as other icons.
This problem also persists in bottom social links display.
![screenshot from 2017-09-18 22-28-53](https://user-images.githubusercontent.com/31239108/30554049-b055e736-9c92-11e7-884f-9955137f5224.png)

2017-09-19 05:30 UTC, dilpreetsio requested changes

2017-09-19 05:30 UTC, geekyd commented on index.html
> +<li><a target="_self" href="https://github.com/fossasia"><i class="fa fa-github fa-lg"></i></a></li>
Please add `class="social-link hidden-md hidden-sm hidden-xs"` to `li` here that will solve the icon alignment issue.

2017-09-19 18:24 UTC, sagar-kalra commented
https://sagar-kalra.github.io/fossasia.org/ 
![screenshot from 2017-09-19 23-54-06](https://user-images.githubusercontent.com/31239108/30608410-c078db0c-9d67-11e7-9d90-f16ad35fe176.png)

2017-09-19 18:26 UTC, geekyd commented
@sagar-kalra Looks good, can you please squash the commits?

2017-09-20 04:09 UTC, sagar-kalra commented
i am trying squashing them into 1, but there is no success yet. Can you help me out? @geekyd

2017-09-20 05:32 UTC, isuruAb commented
@sagar-kalra  follow these steps
git rebase -i HEAD~4
change all picks to squash  excerpt top one
press esc then :wq and enter
again esc then :wq
git push -f origin gh-pages

2017-09-20 05:33 UTC, isuruAb reviewed
@sagar-kalra follow these steps
follow these steps
https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git/#answer-5189600

2017-09-20 05:39 UTC, sagar-kalra commented
when i do rebase it shows all commits i made in different issues also.

2017-09-20 05:48 UTC, isuruAb commented
@sagar-kalra  as a good practise always start every new issue in new branch of master(in this case gh-pages)

2017-09-20 05:48 UTC, sagar-kalra commented
yeah, i made a mistake this time. Is there any solution of this problem now?

2017-09-20 06:38 UTC, isuruAb commented
you can reset your branch
rebase it from upstream/gh-pages and cherry-pick commits that you need for this PR.

2017-09-20 07:58 UTC, sagar-kalra commented
https://sagar-kalra.github.io/fossasia.org/ 
Done.
![screenshot from 2017-09-20 13-28-01](https://user-images.githubusercontent.com/31239108/30632966-73216d02-9dd9-11e7-95b5-334a8dfd8f9e.png)

2017-09-20 09:53 UTC, dilpreetsio approved these changes

2017-09-20 10:40 UTC, merged