Add Sumedh Nimkarde to codeheat mentor list
fossasia/fossasia.org pull request #179
Opened 2017-09-19 12:04 UTC by sumedh123

2017-09-19 12:04 UTC, sumedh123 commented
@geekyd @mariobehling Please take a look.

2017-09-19 12:39 UTC, isuruAb requested changes
@sumedh123  could you please add a little bit small image .  30-40KB image would be good 👍

2017-09-22 12:40 UTC, sumedh123 commented
@isuruAb Please check. I added a smaller sized image.

2017-09-22 13:46 UTC, isuruAb approved these changes

2017-09-22 13:46 UTC, merged