Adding Asitava to Team list
fossasia/fossasia.org pull request #184
Opened 2017-09-23 15:09 UTC by asitava1998

Adds Asitava Sarkar (asitava1998) to the team page

2017-09-23 18:17 UTC, isuruAb requested changes
@asitava1998  could you please add a little bit small photo . 30-40KB one would be good

2017-09-23 18:40 UTC, asitava1998 commented
@isuruAb  Added a smaller photo :+1:

2017-09-24 01:08 UTC, isuruAb approved these changes

2017-09-24 01:08 UTC, merged

2017-09-24 01:09 UTC, isuruAb commented
@asitava1998  thank you very much 👍