Added a developer
fossasia/fossasia.org pull request #223
Opened 2017-12-14 18:10 UTC by samyakbvs

2017-12-14 18:23 UTC, vaibhavsingh97 commented
@samyakbvs PLease share preview link

2017-12-14 18:42 UTC, samyakbvs commented
https://samyakbvs.github.io/samyak-fossasia.org/

2017-12-14 18:53 UTC, kubami9 approved these changes
Works fine

2017-12-14 18:55 UTC, ParthS007 approved these changes

2017-12-14 18:56 UTC, YashKumarVerma approved these changes

2017-12-14 19:03 UTC, vaibhavsingh97 commented
Just a small question 😄 Why you change the developer profile 😅

2017-12-14 19:03 UTC, vaibhavsingh97 approved these changes
LGTM

2017-12-14 19:04 UTC, anshumanv commented
Uneven rows
![image](https://user-images.githubusercontent.com/21009455/34009522-437e59d6-e12f-11e7-99a9-1c661d36a600.png)

2017-12-14 19:04 UTC, anshumanv commented
Also please check, there is no `Alumni` section in your link.

2017-12-14 19:06 UTC, vaibhavsingh97 commented
@anshumanv Thanks for pointing it out

2017-12-14 19:06 UTC, anshumanv requested changes
Check comments.

2017-12-14 19:11 UTC, ParthS007 commented
Thanks @anshumanv for pointing this @samyakbvs Please correct this 👍

2017-12-15 12:15 UTC, isuruAb reviewed
@samyakbvs  please check the rows problem. Add Areeb's photo at the end of the list.

2017-12-15 12:56 UTC, samyakbvs commented
Updated @isuruAb and @anshumanv the code is same as the repo and if you still doubt me then please the the file changed section which clearly show my changes

2017-12-15 12:57 UTC, samyakbvs commented
The alumni code is missing from the repo and I don't think that's my fault?

2017-12-15 13:45 UTC, anshumanv commented
Alumni section is present on the page, please see.

2017-12-15 13:46 UTC, samyakbvs commented
But not in the repo

2017-12-15 13:47 UTC, samyakbvs commented
the code is from the fossasia github repo

2017-12-15 13:50 UTC, samyakbvs commented
@anshumanv

2017-12-15 13:51 UTC, samyakbvs commented
Is it ready to merge then?

2017-12-15 13:56 UTC, anshumanv commented
No, unless those errors are solved, try to find a workaround, read the code well, don't be in a haste to get your PR merged and task approved, the issue is for you to figure out, solve and code.

2017-12-15 13:58 UTC, samyakbvs commented
But why isnt the code in the repo where will i get it from?

2017-12-15 14:00 UTC, anshumanv commented
The code is in the repo :wink: sections won't appear in a website magically.
Please see.

2017-12-15 14:02 UTC, samyakbvs commented
Okay I will

2017-12-15 14:02 UTC, samyakbvs commented
Any other issue?

2017-12-15 14:03 UTC, the-codingninja requested changes
Why you removed a developer from there

2017-12-15 14:05 UTC, anshumanv commented
> Any other issue?

Alumni section and improper rows, solve these two please. :smile:

2017-12-15 14:10 UTC, samyakbvs commented
Okay

2017-12-15 14:11 UTC, samyakbvs commented
Any tips on how to solve them?

2017-12-15 15:13 UTC, samyakbvs commented
I thought that will fix the column issue but it didn't

2017-12-15 15:14 UTC, samyakbvs commented
@ms10398

2017-12-15 15:45 UTC, abishekvashok requested changes

2017-12-15 15:45 UTC, abishekvashok commented on team.html
> +<a href="https://github.com/championswimmer"><i class="icon fa fa-github"></i></a>
Please properly intend the code :)

2017-12-15 15:54 UTC, samyakbvs commented
Can someone pls guide me on how to fix the column issue

2017-12-15 16:03 UTC, samyakbvs commented
@abishekvashok

2017-12-15 16:11 UTC, samyakbvs commented
Finally done @anshumanv

2017-12-15 16:11 UTC, samyakbvs commented
@abishekvashok how would i be able to indent suck a long code?

2017-12-15 16:12 UTC, samyakbvs commented
@ms10398

2017-12-15 16:19 UTC, samyakbvs commented
Please approve without indentation

2017-12-15 17:37 UTC, naveentherocker commented
Try to Squash your Commits

2017-12-15 17:40 UTC, ParthS007 approved these changes

2017-12-15 18:01 UTC, samyakbvs commented
something went wrong creating a new pull request

2017-12-15 18:01 UTC, closed without merging

2017-12-15 18:21 UTC, 0x48piraj reviewed
Messed up!