Adding team member
fossasia/fossasia.org pull request #272
Opened 2018-01-11 19:30 UTC by YashKumarVerma

Adding a new team member

Preview :
https://yashkumarverma.github.io/fossasia.org/team

2018-01-12 04:36 UTC, YashKumarVerma commented
@mariobehling @isuruAb

2018-01-12 11:40 UTC, akshatnitd requested changes

2018-01-12 11:40 UTC, akshatnitd commented on team.html
> +                        <div class="image-holder">
Fix indentation

2018-01-12 19:34 UTC, 0x48piraj requested changes
Remove Conflicts !

2018-01-13 01:22 UTC, isuruAb reviewed
@YashKumarVerma  please resolve conflicts

2018-01-13 04:30 UTC, YashKumarVerma commented
Whops. Fixing in a few hours

2018-01-13 04:58 UTC, YashKumarVerma commented
@isuruAb @0x48piraj @akshatnitd 
Fixed, Resolved, Squashed. 😄

2018-01-13 05:01 UTC, abishekvashok approved these changes

2018-01-13 06:45 UTC, rupav approved these changes

2018-01-13 06:50 UTC, ParthS007 requested changes
@YashKumarVerma  why you are adding team member in between .please add in last of team list.

2018-01-13 06:54 UTC, YashKumarVerma commented
@ParthS007 I don't know why but adding it to last always gave me merge conflicts.

2018-01-13 07:02 UTC, YashKumarVerma commented
@ParthS007 and perhaps this is the only thing i can do 😖

2018-01-13 08:44 UTC, rupav commented
@YashKumarVerma check my comments on your task instance. Thanks.

2018-01-13 09:07 UTC, YashKumarVerma commented
@rupav Sorry but i have abondoned the task because this PR would take time to merge. :/
I couldn't see your message. 😢

2018-01-13 09:26 UTC, YashKumarVerma commented
@rupav got the message from mail. Thanks !

2018-01-13 09:51 UTC, YashKumarVerma commented
@akshatnitd @rupav @ParthS007 @abishekvashok @isuruAb 

Closing this. The merge conflicts came on and on. So started everything from scratch:
# Moved to #274

2018-01-13 09:51 UTC, closed without merging