Changed blur images to suggested one
fossasia/fossasia.org pull request #324
Opened 2018-09-18 20:02 UTC by aditya81070

* Banner image 1
* Banner Image 2
* The FOSSASIA Summit is an annual conference...
* Subscribe to stay informed

2018-09-18 20:04 UTC, aditya81070 commented
@fossasia/gci16-maintainers please review the PR.

2018-09-19 00:44 UTC, abishekvashok reviewed
Can you remove the blured images that you have replaced?

2018-09-19 01:40 UTC, aditya81070 commented
@abishekvashok okay I will do that

2018-09-19 02:21 UTC, aditya81070 commented
@abishekvashok I have removed images.

2018-09-19 03:02 UTC, aditya81070 commented
This last commit fixes #325

2018-09-19 03:03 UTC, aditya81070 commented
@fossasia/gci16-maintainers please review PR.

2018-09-19 07:48 UTC, mariobehling commented
Please provide a test deployment on your own Github account.

2018-09-23 20:34 UTC, samagragupta reviewed
Please provide the issue number and its link .

2018-09-23 20:43 UTC, aayusharora commented
Hi @aditya81070 
Thanks for this :)

It seems like you have added four images but have used only three.
Please remove IMG_6615.jpg, if that is not of the use.

2018-09-24 04:02 UTC, aditya81070 commented
@aayusharora  I just replaced that image with new one.

2018-09-24 04:13 UTC, aditya81070 commented
@mariobehling  Here is my Github development link: [Fossasia](https://aditya81070.github.io/fossasia.org/).

Here are changes as screenshot: -
![screenshot from 2018-09-24 09-37-45](https://user-images.githubusercontent.com/30300772/45937503-4b31cd00-bfde-11e8-9fef-676b28f2a8a5.png)
![screenshot from 2018-09-24 09-37-52](https://user-images.githubusercontent.com/30300772/45937505-4c62fa00-bfde-11e8-930f-07429c518b13.png)
![screenshot from 2018-09-24 09-38-07](https://user-images.githubusercontent.com/30300772/45937506-4e2cbd80-bfde-11e8-91c2-a5724dd15c22.png)
![screenshot from 2018-09-24 09-38-28](https://user-images.githubusercontent.com/30300772/45937508-4f5dea80-bfde-11e8-9e8f-51bbed5fe83a.png)
![screenshot from 2018-09-24 09-38-50](https://user-images.githubusercontent.com/30300772/45937510-5258db00-bfde-11e8-9df3-608e3e10bdd0.png)
![screenshot from 2018-09-24 09-38-54](https://user-images.githubusercontent.com/30300772/45937511-538a0800-bfde-11e8-8c25-fd54351893e7.png)
![screenshot from 2018-09-24 09-39-16](https://user-images.githubusercontent.com/30300772/45937512-54bb3500-bfde-11e8-9d3d-d06a21460b54.png)

2018-09-24 12:14 UTC, samagragupta approved these changes
LGTM

2018-09-26 04:34 UTC, aditya81070 commented
@mariobehling @aayusharora  please see the pull request. if it looks good please merge it.

2018-09-27 18:26 UTC, aditya81070 commented
@mariobehling  @aayusharora please review this pull  request.

2018-10-02 11:01 UTC, abishekvashok requested changes

2018-10-02 11:01 UTC, abishekvashok commented on about/index.html
> -        <meta charset="utf-8">
Please don't change the intendation

2018-10-11 20:24 UTC, aditya81070 commented on about/index.html
> -        <meta charset="utf-8">
This was due to autosave beautify. Should I remove these indentation?

2018-11-18 17:11 UTC, merged