Added Google Code-In 2018 Link
fossasia/fossasia.org pull request #347
Opened 2018-10-26 16:10 UTC by niteshkumarniranjan

2018-10-26 17:58 UTC, akshatnitd reviewed
Please link the issue and fill in the PR description

2018-10-27 19:39 UTC, Akshat-Jain approved these changes
LGTM 👍

2018-10-27 19:43 UTC, akshatnitd reviewed
Provide a demo link and also change `Solving` to `Fixes` in the PR description so that the issue is auto closed on merge.

2018-10-28 05:42 UTC, niteshkumarniranjan commented
@akshatnitd I can't give demo link because I'm creating this PR from other branch. but I will post screenshot.

2018-10-28 09:03 UTC, abishekvashok requested changes

2018-10-28 09:03 UTC, abishekvashok commented on index.html
> +               					     <ul class="nav-dropdown projects" style="min-height: 605px"> <!--whenever you add/remove an option, change the style="min-height:500px" by +- 25px-->
Add 25px not 15px

2018-10-28 09:10 UTC, niteshkumarniranjan commented
@abishekvashok Done!

2018-10-28 09:10 UTC, abishekvashok approved these changes

2018-10-28 09:11 UTC, merged

2018-10-28 09:11 UTC, abishekvashok commented
Thank you