Location link updated
fossasia/fossasia.org pull request #351
Opened 2018-10-28 18:06 UTC by amrs-tech

When clicked, the location marker takes it to the location on Google maps.

2018-10-28 18:07 UTC, amrs-tech commented
This resolves the issue #340

2018-10-28 19:58 UTC, YashKumarVerma approved these changes

2018-10-29 02:07 UTC, supunTE requested changes
I think we can see the change if there's a preview link.

2018-10-29 06:32 UTC, amrs-tech commented
I'll try to come up with a preview link

2018-10-29 10:38 UTC, YashKumarVerma commented
do we really need a preview link to see if an anchor tag is working :confused:  @STEdirisuriya

2018-10-29 11:17 UTC, sarnava1 approved these changes
LGTM

2018-10-31 03:47 UTC, amrs-tech commented
Actually I'm sorry guys i could not come up with a screenshot because my laptop is not working and I've done this PR using my mobile. Please someone ask the maintainer to check this PR and merge it. Thanks :)

2018-11-01 17:48 UTC, samagragupta approved these changes

2018-11-02 03:58 UTC, abishekvashok approved these changes

2018-11-02 03:58 UTC, merged