index: make navbar responsive
fossasia/fossasia.org pull request #404
Opened 2018-11-29 06:36 UTC by AdityaSrivast

Fixes: #386 

Expected Behaviour: Currently the navbar is not responsive. But, it should be responsive.

Deployment Link: https://adityasrivast.github.io/fossasia.org/

2018-12-02 12:29 UTC, samagragupta requested changes
Please resolve the conflicts.

2018-12-02 13:01 UTC, AdityaSrivast commented
@samagragupta I have made the changes. Please review

2018-12-04 04:15 UTC, Ryan10145 commented
@AdityaSrivast There are still more conflicts now that must be resolved.

2018-12-04 08:36 UTC, aayusharora requested changes

2018-12-04 08:36 UTC, aayusharora commented on css/custom.css
> +    padding: 0px 3px;
Remove px from 0

2018-12-04 08:37 UTC, aayusharora commented
@AdityaSrivast please check the suggestions

2018-12-04 08:40 UTC, sarnava1 requested changes
@AdityaSrivast please resolve the conflicts

2018-12-06 06:45 UTC, AdityaSrivast commented
@aayusharora @samagragupta Can you please review again? Also merge if in order. This is the second time I am updating this PR for merge conflicts :sweat_smile:

2018-12-06 06:58 UTC, samagragupta requested changes
![navbar](https://user-images.githubusercontent.com/32234926/49566937-55633680-f952-11e8-8d6b-047e544b2596.PNG)
There is problem in nav-bar at `1199px x 754px`

2018-12-06 07:05 UTC, AdityaSrivast commented
![image](https://user-images.githubusercontent.com/31389740/49567138-dfab9a80-f952-11e8-9743-74999a1fc239.png)
@samagragupta it's working fine for me in chrome, firefox and opera. Which browser are you using?

2018-12-06 12:37 UTC, samagragupta reviewed
@sarnava1 @aayusharora What are your views?
![navbar](https://user-images.githubusercontent.com/32234926/49584526-9fafdc00-f981-11e8-89b7-f423471677a6.PNG)
I am using chrome.

2018-12-10 19:34 UTC, jakubpawlina requested changes
There is no way to enter the menu:
![zrzut ekranu 136](https://user-images.githubusercontent.com/29257057/49756727-efacdc80-fcba-11e8-9831-ae26ddb8d16e.png)

2018-12-25 17:55 UTC, mariobehling commented
Closing this issue as there is no follow up anymore.

2018-12-25 17:55 UTC, closed without merging