Made  "arrow" on dropdown for GCI submenu showing to the ">" right
fossasia/fossasia.org pull request #463
Opened 2018-12-26 07:26 UTC by Dharmesh-Poddar

#461 
![screenshot from 2018-12-26 12-56-07](https://user-images.githubusercontent.com/32756751/50436852-b0fb6100-090d-11e9-9262-cfee98af38ed.png)

2018-12-26 08:18 UTC, Dharmesh-Poddar commented
@abishekvashok  please review..

2018-12-27 08:20 UTC, plxity commented
LGTM 👍

2018-12-27 14:20 UTC, KSNINJA commented
Please provide a preview link

2018-12-27 14:25 UTC, Dharmesh-Poddar commented
@KSNINJA https://loving-mahavira-1fd963.netlify.com

2018-12-28 06:50 UTC, abishekvashok requested changes

2018-12-28 06:50 UTC, abishekvashok commented on css/custom.css
> +}
Please remove this space

2018-12-28 06:50 UTC, abishekvashok commented on css/custom.css
> + .has-submenu{
Please remove this space

2019-01-02 13:36 UTC, merged