Back to top button added
fossasia/fossasia.org pull request #484
Opened 2019-02-17 10:18 UTC by imrrahul

In this Pull Request I have solved the issues #474  #197  ,i.e, added the back to top button as previous back to top link was not properly visible.
- Fixes #474 #197 

## Screenshot
![screenshot from 2019-02-17 15-46-34](https://user-images.githubusercontent.com/37583853/52911556-6540b480-32cb-11e9-9a46-0bfb43bead14.png)

## Preview link
https://imrrahul.github.io/fosssasia.org/

2019-02-18 13:31 UTC, imrrahul commented
@realslimshanky review this PR.

2019-03-13 18:46 UTC, abhinavsagar approved these changes

2019-04-10 17:55 UTC, samagragupta approved these changes

2019-04-10 17:55 UTC, samagragupta reviewed
Please resolve conflicts.

2019-04-11 12:07 UTC, abishekvashok requested changes

2019-04-11 12:07 UTC, abishekvashok commented on about/index.html
> +
Remind this empty line and move the script to script.js

2019-07-19 09:44 UTC, mariobehling commented
It was a good start, but such a pity you did not finish this. Closing it therefore.

2019-07-19 09:44 UTC, closed without merging