Added Badge Magic to Apps
fossasia/fossasia.org pull request #520
Opened 2019-06-21 09:00 UTC by adityastic

2019-06-21 09:03 UTC, adityastic commented
@mariobehling please review

2019-06-21 18:37 UTC, mariobehling requested changes
In order to keep the design consistent, please also add the two other apps, keep the size consistent and ensure all points in the issue are taken care. Thank you

2019-06-22 02:38 UTC, adityastic commented
@mariobehling can you give me an example of semi-transparent background with app name on top? so i can visualize your idea well

2019-06-22 02:53 UTC, adityastic commented
> add a semitransparent background and text with the app name on the bottom of the app screenshots

@mariobehling I am not able to visualize the design you are looking for, can you explain to me with a screenshot of something which is similar to the expected outcome?

2019-06-28 17:54 UTC, kushthedude commented
> > add a semitransparent background and text with the app name on the bottom of the app screenshots
> 
> @mariobehling I am not able to visualize the design you are looking for, can you explain to me with a screenshot of something which is similar to the expected outcome?

@adityastic Since you see there are three apps on one row, I suggest you add Open Event Attendee and Open Event Orga app too

2019-06-28 17:55 UTC, kushthedude requested changes
@adityastic Since you see there are three apps on one row, I suggest you add Open Event Attendee and Open Event Orga app too

2019-06-28 17:55 UTC, kushthedude requested changes
Optimise the jpg file, 327kb is too high it will increase load time by a good amount

2019-06-29 04:22 UTC, adityastic commented
@kushthedude yeah I get that part. But check the issue description, it states to add a semi transparent bg with the app name on the bottom. No idea where to use the background semi translucent. There must be an image inside Mario's head, I want him to explain to me about it

2019-07-19 09:43 UTC, mariobehling commented
Please add the other apps first and progress to open questions in a follow up PR afterwards.

2019-07-19 10:20 UTC, adityastic commented
Ohk

2019-07-19 10:50 UTC, adityastic commented
@mariobehling updated

<img width="1436" alt="Screenshot 2019-07-19 at 4 20 11 PM" src="https://user-images.githubusercontent.com/11988517/61530226-1c8b5400-aa41-11e9-95a0-1838ede87a29.png">
<img width="1436" alt="Screenshot 2019-07-19 at 4 20 17 PM" src="https://user-images.githubusercontent.com/11988517/61530237-2319cb80-aa41-11e9-983f-a881c1c6e993.png">

2019-07-19 11:27 UTC, mariobehling requested changes
1. Please don't add the logos except for Badge Magic. There is already a logo of eventyay.
2. All screenshots need to be conform in the same size.

2019-07-19 11:37 UTC, adityastic commented
@ShridharGoel give me a recent screenshot of orga app

2019-07-19 16:11 UTC, ShridharGoel commented
![Dashboard - Orga App](https://user-images.githubusercontent.com/35566748/61549531-e44e3a80-aa6d-11e9-930b-a2307e3fe75c.png)

2019-07-19 16:16 UTC, ShridharGoel commented
![Dashboard - Orga App](https://user-images.githubusercontent.com/35566748/61549806-971e9880-aa6e-11e9-82f7-e939fb1923df.png)

2019-07-31 09:06 UTC, adityastic commented
@mariobehling updated

<img width="1436" alt="Screenshot 2019-07-31 at 2 33 42 PM" src="https://user-images.githubusercontent.com/11988517/62198942-36615b00-b3a0-11e9-960c-93a9dd9dde04.png">

2019-08-01 07:51 UTC, ShridharGoel commented
@adityastic Why not using the Event Dashboard screenshot for Orga App? The one which I provided.

2019-08-01 08:24 UTC, adityastic commented
@ShridharGoel the screen ratio was different. If you can provide me a screenshot with a modern ratio, I can use it

2019-08-05 05:36 UTC, adityastic commented
@mariobehling plz update

2019-08-05 05:39 UTC, kushthedude commented
> @mariobehling plz update

@adityastic Please provide Deployment Link.

2019-08-05 05:58 UTC, adityastic commented
@kushthedude Already did, please check the pr

2019-08-05 06:11 UTC, kushthedude commented
> @kushthedude Already did, please check the pr

Can you please point it out?

2019-08-05 07:20 UTC, adityastic commented on index.html
> +									<a href="https://play.google.com/store/apps/details?id=org.fossasia.badgemagic">
@kushthedude and many more

2019-08-05 07:53 UTC, kushthedude commented
I am asking deployment link for the pr buddy

On Mon, 5 Aug 2019 at 12:50 PM, Aditya Gupta <notifications@github.com>
wrote:

> *@adityastic* commented on this pull request.
> ------------------------------
>
> In index.html
> <https://github.com/fossasia/fossasia.org/pull/520#discussion_r310466071>:
>
> > @@ -551,6 +558,29 @@ <h1>Android Apps of FOSSASIA</h1>
>  							</div>
>
>  						</div>
> +					<div class="row">
> +							<div class="col-md-4 col-sm-12 sponsor-column"  >
> +								<div class=" text-center" style="margin-bottom: 30px">
> +									<a href="https://play.google.com/store/apps/details?id=org.fossasia.badgemagic">
>
> @kushthedude <https://github.com/kushthedude> and many more
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/fossasia/fossasia.org/pull/520?email_source=notifications&email_token=AKQMTLUM3QGBC3G2JAPBNJ3QC7IDNA5CNFSM4H2PCG22YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCAQO2QI#pullrequestreview-270593345>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AKQMTLW32X5FEP3SL2VWIVTQC7IDNANCNFSM4H2PCG2Q>
> .
>

2019-08-05 08:53 UTC, adityastic commented
@kushthedude you seriously want me to deploy the app just to add 4 images to the website? Like Seriously?

2019-08-05 08:54 UTC, kushthedude commented
Responsiveness Check😏

On Mon, 5 Aug 2019 at 2:23 PM, Aditya Gupta <notifications@github.com>
wrote:

> @kushthedude <https://github.com/kushthedude> you seriously want me to
> deploy the app just to add 4 images to the website? Like Seriously?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/fossasia/fossasia.org/pull/520?email_source=notifications&email_token=AKQMTLXSHJG4XS5ZU66T2EDQC7S7NA5CNFSM4H2PCG22YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3RETTQ#issuecomment-518146510>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AKQMTLSSCAH4CF7FFP5KYXDQC7S7NANCNFSM4H2PCG2Q>
> .
>

2019-08-05 13:09 UTC, abishekvashok approved these changes
LGTM

2019-08-05 14:36 UTC, adityastic commented
@kushthedude not sure what you meant by responsive images. Please Elaborate

2019-08-08 09:24 UTC, merged