Adding a team member to the website
fossasia/fossasia.org pull request #565
Opened 2019-12-05 02:43 UTC by Hasala123

Added a new section for team members in the site for a GCI task.
Had to remove content in CNAME folder so that i can host it as well. (can't host many site with same CNAME)

2019-12-05 04:27 UTC, liveHarshit requested changes
?

2019-12-05 05:48 UTC, nikit19 requested changes
If you remove the CNAME then on what URL will the site open? Please don't do that. Also see how other team members have been added and don't add your own details there

2019-12-05 16:31 UTC, mariobehling commented
Add a link to a test page.

2019-12-08 09:49 UTC, abishekvashok requested changes
Intend code + add an existing member

2019-12-08 09:49 UTC, abishekvashok commented on CNAME
> +
Please don't remove this file. It's required for GitHub to identify the domain

2019-12-17 16:09 UTC, mariobehling commented
Closing this due to inactivity.

2019-12-17 16:09 UTC, closed without merging