Add more Profile Icons and Links to Page Bottoms
fossasia/fossasia.org pull request #590
Opened 2019-12-19 12:47 UTC by kumuditha-udayanga

# Purpose 
The purpose of this PR is to fix issue #582 

# Approach
- Add custom SVG files for missing font-awesome logos.
- Add Docker and Crunchbase links and logos to the footer of relevant pages.

# Preview
https://kumuditha-udayanga.github.io/fossasia.org

# Screenshot

<img width="1658" alt="Screenshot 2019-12-19 at 18 15 57" src="https://user-images.githubusercontent.com/27630091/71174639-b32b9d80-228b-11ea-9faf-bfcefc58bb3c.png">

2019-12-19 12:51 UTC, liveHarshit requested changes
Open links with a new tab

2019-12-19 15:44 UTC, kumuditha-udayanga commented
@liveHarshit Changers are done :)

2019-12-20 05:30 UTC, liveHarshit approved these changes

2019-12-21 00:22 UTC, mariobehling commented on img/crunchbase.svg
> +        <path d="M71.47,63c-6.16-.08-10.59-4.35-10.58-10.2,0-6.14,4.65-11,10.5-10.92,6.17,0,10.59,4.91,10.52,11.56C81.86,58.81,77.2,63.07,71.47,63Z"/>
what is this? While most browsers could show svgs, they dont always look the same everywhere. So, please stay with the existing way to display icons.

2019-12-21 00:24 UTC, mariobehling commented on img/crunchbase.svg
> +        <path d="M71.47,63c-6.16-.08-10.59-4.35-10.58-10.2,0-6.14,4.65-11,10.5-10.92,6.17,0,10.59,4.91,10.52,11.56C81.86,58.81,77.2,63.07,71.47,63Z"/>
Or am I wrong? @liveHarshit as you accepted this. Should we try?

2019-12-21 00:24 UTC, mariobehling commented
Please resolve conflicts in any case. Thanks

2019-12-22 10:46 UTC, closed without merging