Solved the issue for title overlay of the android app cards
fossasia/fossasia.org pull request #598
Opened 2019-12-21 18:50 UTC by harsh-kukreja

Overlay mobile view aligned.
Changed the overlay text color to white.
Fixed pixelated images
For issue #541

2019-12-21 18:54 UTC, harsh-kukreja commented
Hey @mariobehling here is correct pr, deployment [link](https://harsh-kukreja.github.io/harsh-fossasia.org/)

2019-12-22 23:23 UTC, mariobehling requested changes
I see a number of unrelated changes to this issue and only a very small part of the issue is solved.
Not sure, why css/text-overlay.css should be deleted. Please use CSS instead of html e.g. "strong" tag. Thanks

2019-12-23 10:01 UTC, harsh-kukreja commented
Hey @mariobehling i changed some css and wrote that into custom.css instead of text-overlay.css according to the conventions and strong tag was used before there was a font tag also which was used but i will remove the strong tag also

2019-12-31 10:35 UTC, mariobehling approved these changes

2019-12-31 10:35 UTC, merged