added new team member
fossasia/fossasia.org pull request #604
Opened 2019-12-23 15:42 UTC by chamodperera

preview link-https://chamodperera.github.io/fossasia.org/team/

![team member](https://user-images.githubusercontent.com/39716499/71366699-cced1d80-25c8-11ea-83c7-754352fc48c6.png)

2019-12-23 15:43 UTC, chamodperera commented
@mariobehling please accept

2019-12-23 16:02 UTC, kumuditha-udayanga commented
LGTM 😇

2019-12-23 16:22 UTC, mariobehling commented
GitHub link is wrong. We also need a better photo, please. @atm1504 Please help with a better quality image.

2019-12-24 06:08 UTC, atm1504 commented
> GitHub link is wrong. We also need a better photo, please. @atm1504 Please help with a better quality image.

Yah sure. I am giving the required data

2019-12-24 06:11 UTC, atm1504 requested changes

2019-12-24 06:11 UTC, atm1504 commented on team/index.html
> +									<a href="<a href="https://github.com/neel1998" target="blank"><i class="icon fa fa-github"></i></a>" target="blank"><i class="icon fa fa-github"></i></a>
Wrong GitHub link. Please change it. The correct link should be ```https://github.com/atm1504```.
Wrong spelling in alt tag

2019-12-24 06:11 UTC, atm1504 commented on team/index.html
> +						<span class="speaker-name">Amrtya Mondal</span>
Spelling wrong. Correct spelling is ```Amartya Mondal```

2019-12-24 06:18 UTC, atm1504 commented
![atm](https://user-images.githubusercontent.com/43731599/71397291-23973d80-2643-11ea-904c-8afadb9bbe14.jpeg)
@chamodperera please use this image

2019-12-24 12:57 UTC, chamodperera commented
@atm1504  @mariobehling  Changes have been done

![git3](https://user-images.githubusercontent.com/39716499/71414018-f5355480-267a-11ea-8f26-8cb0bf2978f6.png)

2019-12-24 13:27 UTC, anishagg17 requested changes
I think you should squash  all your commits.

2019-12-24 14:03 UTC, liveHarshit requested changes
You're updating one team member but adding three photos, why? Also update the PR title to be specific, whom you are adding.

2019-12-24 15:05 UTC, closed without merging