Add missing profile links of team members
fossasia/fossasia.org pull request #612
Opened 2019-12-24 11:33 UTC by kumuditha-udayanga

# Purpose 
The purpose of this PR is to add the missing profile links of the team members on the team page(GitHub, Facebook, LinkedIn, Twitter).

# Approach
- Add Shubham Padia's Linkedin profile link.
- Add Sudheesh Singanamalla's Linkedin, Facebook, Twitter profile links.
- Add Hong Phuc Dang's Facebook profile link.
- Add Isuru Abeywardana Facebook profile link.

# Preview link
https://kumuditha-udayanga.github.io/fossasia.org/team/

# Screenshots

<img width="536" alt="Screenshot 2019-12-24 at 16 56 55" src="https://user-images.githubusercontent.com/27630091/71411280-a71a5400-266e-11ea-8bc2-7e257f18eff2.png">

<img width="312" alt="Screenshot 2019-12-24 at 16 57 15" src="https://user-images.githubusercontent.com/27630091/71411290-b1d4e900-266e-11ea-878d-14b819c12e0b.png">

<img width="565" alt="Screenshot 2019-12-24 at 16 57 33" src="https://user-images.githubusercontent.com/27630091/71411307-bdc0ab00-266e-11ea-9dcc-1b2424c83310.png">

<img width="291" alt="Screenshot 2019-12-24 at 16 59 59" src="https://user-images.githubusercontent.com/27630091/71411385-13955300-266f-11ea-8267-18e4d5944b4d.png">

2019-12-24 11:35 UTC, kumuditha-udayanga commented
@mariobehling It would be nice to have your reviews :)

2019-12-24 14:06 UTC, liveHarshit requested changes
What if developers do not want other profile links? Team members added the links from their self.

2019-12-24 14:35 UTC, kumuditha-udayanga commented
@liveHarshit In the task ( https://codein.withgoogle.com/tasks/5080003218243584/?sp-organization=5183942706069504&sp-is_beginner=False ) it says to update the page because of partly outdated and lacking team members and links. So I searched the missing profiles and add them.

2019-12-25 06:18 UTC, liveHarshit approved these changes

2019-12-27 06:17 UTC, kumuditha-udayanga commented
@mariobehling please review and merge :)

2019-12-27 09:02 UTC, mariobehling approved these changes

2019-12-27 09:02 UTC, merged