fix responsive image from team page. from issue #623
fossasia/fossasia.org pull request #624
Opened 2019-12-31 15:39 UTC by adiwahyudi02

2019-12-31 15:43 UTC, adiwahyudi02 commented
![result](https://user-images.githubusercontent.com/45607028/71626277-f805eb80-2c1e-11ea-8ef1-5da04898c319.png)

2019-12-31 19:12 UTC, pranav1698 reviewed
Please write a description to your pr and link an issue which you have solved.

2020-01-02 00:08 UTC, adiwahyudi02 commented
Could you please check it now? @pranav1698 
https://adiwahyudi02.github.io/fossasia.org/team/

2020-01-04 17:55 UTC, pranav1698 requested changes

2020-01-04 17:55 UTC, pranav1698 commented on css/theme-lava.css
> +  text-align: center;
Same here

2020-01-04 17:55 UTC, pranav1698 commented on css/theme-lava.css
> +/* .speaker .image-holder {
No need to add another block of code 
You can insert your changes in the same block

2020-01-05 05:07 UTC, adiwahyudi02 commented
I have updated it. please review again @pranav1698

2020-01-05 11:14 UTC, pranav1698 approved these changes

2020-01-05 11:15 UTC, pranav1698 commented
Please wait for someone with write access to merge the pr
@mariobehling

2020-01-05 11:17 UTC, merged