Update index.html
fossasia/fossasia.org pull request #628
Opened 2020-01-05 06:37 UTC by coder135792468

Added missing icons as per #582 
Preview link: https://coder135792468.github.io/fossasia.org/

2020-01-05 07:26 UTC, NishithP2004 approved these changes
Great work with the crunch base icon but as a suggestion, could you please make it black and white to meet the other icons.

2020-01-05 07:41 UTC, coder135792468 commented
@NishithP2004 thanks I fixed it now the icon is matched to the other icons

2020-01-05 07:45 UTC, NishithP2004 approved these changes
Great Work 👍

2020-01-05 16:51 UTC, abishekvashok commented
It doesn't look responsive in Mobile. Please take a look

2020-01-05 16:53 UTC, abishekvashok requested changes
Please intend the code as well

2020-01-05 16:53 UTC, abishekvashok commented on index.html
> +   <img style="width:20px;height:20px" src="http://gecad.com/wp-content/themes/gecad/assets/images/icon-crunchbase-black.svg"/>
Instead of using an svg, please use an icon provided by an imported icon pack (font awesome?)

2020-01-05 17:46 UTC, NishithP2004 commented
That's the issue, Crunchbase isn't available in the Font awesome library.

On Sun, 5 Jan 2020, 10:23 pm Abishek V Ashok, <notifications@github.com>
wrote:

> *@abishekvashok* requested changes on this pull request.
>
> Please intend the code as well
> ------------------------------
>
> In index.html
> <https://github.com/fossasia/fossasia.org/pull/628#discussion_r363104740>:
>
> >
> +<a target="_self" href="https://www.crunchbase.com/organization/fossasia">
> +   <img style="width:20px;height:20px" src="http://gecad.com/wp-content/themes/gecad/assets/images/icon-crunchbase-black.svg"/>
>
> Instead of using an svg, please use an icon provided by an imported icon
> pack (font awesome?)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/fossasia/fossasia.org/pull/628?email_source=notifications&email_token=AIHZ3NHOZCW2YG7IATQD5D3Q4IF7FA5CNFSM4KCZYRWKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCQV32AY#pullrequestreview-338410755>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIHZ3NBT2KDMLARLNEFKAW3Q4IF7FANCNFSM4KCZYRWA>
> .
>

2020-01-06 00:26 UTC, coder135792468 commented
@abishekvashok Sir crunch base icon not available in font awesome

2020-01-06 06:25 UTC, pranavkarthik10 commented
LGTM but if icon pack required, try a different one other than font awesome?

2020-01-06 06:36 UTC, coder135792468 commented
@pranavkarthik10 I can't any package of icons in which cruchbase icon is given so I add it using image

2020-01-06 15:25 UTC, coder135792468 commented
@abishekvashok  plz reply it going 2days without any reply

2020-01-08 03:20 UTC, coder135792468 commented
@mariobehling @hpdang or any other mentor plz look at this PR it's going for a 6 days without any reply

2020-01-08 03:39 UTC, mariobehling requested changes
Well, instead of hosting the file externally, please add it to the image folder.

2020-01-08 11:39 UTC, coder135792468 commented
@mariobehling please take a look and merge it

2020-01-08 17:44 UTC, mariobehling requested changes
This was tried already by several people. The approach breaks the display of Github icons in other areas.

2020-01-09 01:10 UTC, coder135792468 commented
@mariobehling this is a task of gci .so Please merge it. 
And please tell me what is the problems in the code ?

2020-01-09 01:12 UTC, pranavkarthik10 commented
@coder135792468 This requires an update of font awesome, which requires a change of all the github icons website wide. Without changing each to fab, they will be rendered incorrectly.

2020-01-09 03:16 UTC, coder135792468 commented
@pranavkarthik10 bro crunch base icon is not in any font awesome library . And other icons are added correctly .
You can see them by preview links

2020-01-09 09:54 UTC, mariobehling commented
Changes result in not showing the GitHub icon on team page anymore: https://coder135792468.github.io/fossasia.org/team/

The code for the existing icons should not be changed.

2020-01-09 11:22 UTC, coder135792468 commented
@mariobehling sir the changes are showing
![Screenshot_2020-01-09-17-00-15-35](https://user-images.githubusercontent.com/56873740/72063691-45114e00-3300-11ea-9b3f-231e6a432cb9.png)

Look at it please

2020-01-10 15:42 UTC, coder135792468 commented
@mariobehling @hpdang plz review and merge it

2020-01-12 03:12 UTC, coder135792468 commented
@mariobehling @hpdang anyone plz merge it

2020-01-20 15:00 UTC, coder135792468 commented
@abishekvashok @mariobehling @hpdang @cweitat anyone please see it .
No one is replying .
Any mentor plz review it 🙏🙏🙏🙏🙏🙏🙏🙏

2020-08-31 02:41 UTC, closed without merging