Dynamic Scroll Added for Dropdowns. Removed Hardcoded CSS from Homepage
fossasia/fossasia.org pull request #63
Opened 2016-09-29 20:14 UTC by Shivang-Bhandari

I have changed a property in the CSS which is helpful for the developers as it adds the list items of the navbar into a scrollable menu which keeps the height of the dropdown fixed and the developer doesn't have to manually add to the value of the inline css everytime a list item is added or removed. Moreover, it would be helpful in maintaining the responsiveness as hardcoding the height of the list would not give a decent UX.
(https://cloud.githubusercontent.com/assets/16368588/18970508/310b99a2-86af-11e6-9b47-1585ae120901.png)

2016-09-29 20:17 UTC, the-dagger commented
@Shivang-Bhandari  Looks good to me :+1:

2016-09-29 20:22 UTC, Shivang-Bhandari commented
@the-dagger Thanks :)

2016-09-30 17:47 UTC, jig08 commented
@Shivang-Bhandari Attach a link of the demo for easier testing and quick review of PRs :)

2016-10-02 02:02 UTC, daminisatya commented
@Shivang-Bhandari is the scroll bar next to the website expected?  Did it regress from your current change or is it already exisiting?  Also i see two commits , please squash them into one single commit and follow the pattern ``` fixes #issuenumber ...``` .

2016-10-02 02:04 UTC, daminisatya requested changes
Please remove the unnecessary space changes in your file. Very hard to review for spacings

2016-10-02 07:14 UTC, Shivang-Bhandari commented
@jig08 https://shivang-bhandari.github.io/fossasia.org/ is the link to review the scroll added for the navbar dropdown elements.

2016-10-02 09:59 UTC, closed without merging