Add Weibo, VK, Linkedin Icon to Drop Down Menu
fossasia/fossasia.org pull request #642
Opened 2020-01-10 14:57 UTC by hoangdatngo

## Purpose
The purpose of this PR is to add Weibo, VK, and Linkedin icon to drop down menu.
## Preview
Preview link: https://hoangdatngo.github.io/fossasia.org/

@mariobehling, @kushthedude, @hpdang, @prateekiiest Can any mentor please review my PR?

2020-01-11 14:34 UTC, hoangdatngo commented
@prateekiiest, @liveHarshit, @mariobehling, @cweitat Can any mentor please review it. I have been waiting for over 36 hours

2020-01-12 02:22 UTC, hoangdatngo commented
@kushthedude Can you please review my PR?

2020-01-12 06:03 UTC, cweitat requested changes
please follow the current way of typing is . `<a href="" target=""/>` not `<a target="" href="">`

2020-01-12 08:29 UTC, hoangdatngo commented
@mariobehling Can you please review and merge my MR?

2020-01-12 10:30 UTC, cweitat approved these changes

2020-01-12 13:12 UTC, hoangdatngo commented
@liveHarshit, @cweitat Can any mentor merge my PR please

2020-01-13 02:52 UTC, abishekvashok requested changes
Please rebase properly, this contain possible changes from another pr not relating to the issue

2020-01-13 17:37 UTC, prateekj117 requested changes

2020-01-13 17:37 UTC, prateekj117 commented on CNAME
> +fossasia.org
No changes required in this file.

2020-08-31 02:41 UTC, closed without merging