Increases the gap between the rows of icons
fossasia/fossasia.org pull request #655
Opened 2020-01-18 20:09 UTC by mohitm15

Fixes #654 

**Screenshot**

![Screenshot 2020-01-19 01:24:28](https://user-images.githubusercontent.com/35539313/72669820-7a364280-3a5c-11ea-80e1-6495b6bb763b.png)

2020-01-18 20:10 UTC, mohitm15 commented
@mariobehling review this

2020-01-20 04:58 UTC, prateekiiest commented
@mariobehling would it be fine, if I am reviewing this PR since I am actually not mentoring this year.
I would still be nevertheless happy to do so.

2020-03-03 18:00 UTC, Chaitanyassr approved these changes

2020-03-08 09:48 UTC, abishekvashok requested changes

2020-03-08 09:48 UTC, abishekvashok commented on index.html
> +								<br><br><br>
Not a robust solution when in desktop mode

2020-05-13 01:50 UTC, prateekiiest commented
Is this not resolved yet?

2020-08-31 02:41 UTC, closed without merging