Fixed License Contributor button [Issue #674]
fossasia/fossasia.org pull request #675
Opened 2020-02-12 05:23 UTC by AbhinavMir

Solved the issue https://github.com/fossasia/fossasia.org/issues/674

View it here: https://ibb.co/2kSC5V8

2020-03-03 17:58 UTC, Chaitanyassr requested changes
please edit the respective css file.

2020-03-08 09:49 UTC, abishekvashok requested changes

2020-03-08 09:49 UTC, abishekvashok commented on licenses/debug.log
> +[0212/102906.642:ERROR:crash_report_database_win.cc(428)] unexpected header
Unwanted change

2020-03-08 09:49 UTC, abishekvashok commented on licenses/index.html
> +							<a href="https://fossasia.org/cla/" class="btn btn-hollow" target="_self" style="padding:1.2vw">Contributor License Agreement</a>
Don't make use of inline styles, please use the custom css file

2020-09-28 16:39 UTC, mariobehling commented
Missing details, missing screenshots. Therefore closing it.

2020-09-28 16:39 UTC, closed without merging