Fixes #673 : Text overlaps with header in License Agreements section of the page
fossasia/fossasia.org pull request #677
Opened 2020-02-12 16:45 UTC by bharat-1809

This pull request fixes #673 
Added a line break to prevent text from overlapping with the header

Here are screenshots:
BEFORE

![Screenshot from 2020-02-12 22-06-49](https://user-images.githubusercontent.com/58745044/74356589-9d96a800-4de4-11ea-945c-82b4c5849e3d.png)

AFTER

![Screenshot from 2020-02-12 22-06-06](https://user-images.githubusercontent.com/58745044/74356709-cf0f7380-4de4-11ea-84c4-f4c21288fa6d.png)

Here's the deployed link:
https://bharat-1809.github.io/fossasia.org/licenses

2020-02-12 16:55 UTC, yashLadha reviewed
Changes look good. It would be great if you can rebase your commit in one.

2020-02-12 18:42 UTC, bharat-1809 commented
@yashLadha I have rebased all the commits in one.

Thanks for reviewing

2020-02-12 18:43 UTC, yashLadha approved these changes

2020-02-15 15:00 UTC, Chaitanyassr requested changes
Still not working in my browser, please check ones.
![Screenshot (161)](https://user-images.githubusercontent.com/30374226/74590163-e2634e80-5031-11ea-87ac-a9e5b4003655.png)

2020-02-15 22:47 UTC, bharat-1809 commented
@Chaitanyassr 
The problem with the page was that ```<br style="line-height: x">``` does not have cross platform functionality so it was working fine in Firefox while not in Chrome. I have added a new class in custom.css to create a blank box that solves the problem
I have made the necessary changes and the page works as desired
Here's a screenshot:

![Screenshot_20200216-035829_Chrome](https://user-images.githubusercontent.com/58745044/74596280-0a26d680-5073-11ea-9ac9-af4c9cdfcc51.jpg)

Here's the link:
https://bharat-1809.github.io/fossasia.org/licenses/

Thanks

2020-02-16 05:02 UTC, Chaitanyassr approved these changes
Works for me.

2020-02-16 13:05 UTC, abishekvashok requested changes
Now the contributor license agreement looks weird

2020-02-16 13:57 UTC, bharat-1809 commented
@abishekvashok 
The above screenshot was of desktop view on mobile phone and the License Agreement Section do looks weird in that, however the look of the page is different in pure mobile and desktop view. Below are the screenshots:

**Mobile View:**

![Screenshot_20200216-185341_Chrome](https://user-images.githubusercontent.com/58745044/74605469-6418b200-50ee-11ea-8ed1-e1efc69ec61f.jpg)


**Desktop View:**

![Screenshot from 2020-02-16 18-51-10](https://user-images.githubusercontent.com/58745044/74605474-6da21a00-50ee-11ea-8457-5824d160c06c.png)

**Link to the deployed page:**
https://bharat-1809.github.io/fossasia.org/licenses/

2020-02-16 14:40 UTC, abishekvashok reviewed
The code works! But I do have a suggestion, since we are using bootstrap theme, can we use its components to offer the required spacing instead of custom css?

2020-02-16 19:19 UTC, bharat-1809 commented
@abishekvashok 
I have removed the custom class from the custom.css and instead used "pagination" class in bootstrap.css to solve the issue.
I have used ```.pagination``` class alongwith ```<br>``` to create a blank space to prevent overlappinng of text.

Here's the link: https://bharat-1809.github.io/fossasia.org/licenses

Thanks

2020-02-21 23:53 UTC, bharat-1809 commented
@abishekvashok 
I have now used 'row' class alongwith height as style to prevent the overlapping

Here's the link:
https://bharat-1809.github.io/fossasia.org/licenses/

Thanks

2020-03-03 10:34 UTC, abishekvashok approved these changes
Lanky but WORKS

2020-07-21 15:23 UTC, Raunaksingh100 approved these changes

2020-09-28 16:45 UTC, mariobehling commented
Already resolved.

2020-09-28 16:45 UTC, closed without merging