Text hidden
fossasia/fossasia.org pull request #685
Opened 2020-03-21 06:39 UTC by Sohan022

Some text are hidden in "A little more about FOSSASIA" corrected.
fixed: #684 
preview link: https://sohan022.github.io/fossasia.org/

2020-03-21 18:50 UTC, Chaitanyassr requested changes
Greate, Please squash the commit.

2020-03-21 18:50 UTC, Chaitanyassr commented on index.html
> -							<a href="img/DSC_0502_1_0.JPG" data-lightbox="true" data-title="Lightbox Image">
Why changing the name of the image?

2020-03-28 20:07 UTC, Sohan022 commented
I'm creating a new pull request due to some mistake in this branch of the repo.

2020-04-29 13:02 UTC, Chaitanyassr commented
> I'm creating a new pull request due to some mistake in this branch of the repo.

Close the old one.

2020-09-26 10:39 UTC, Raunaksingh100 reviewed
You can closed this pr because you create a new pr for this same issue

2020-09-26 10:48 UTC, closed without merging