popup corrected
fossasia/fossasia.org pull request #687
Opened 2020-03-28 21:03 UTC by Sohan022

On clicking, different images popup in memories section of FOSSASIA corrected

fixed: #664

preview link: https://sohan022.github.io/fossasia.org/

2020-03-28 21:38 UTC, Chaitanyassr requested changes

2020-03-28 21:38 UTC, Chaitanyassr commented on index.html
> +								<span>© Copyright 2009-2019 Creative Commons By License, FOSSASIA</span>
Why change 2020 to 2019?

2020-03-28 21:38 UTC, Chaitanyassr commented on index.html
> +									<p><div>At FOSSASIA Labs we are collecting ideas for new features of our applications and entirely new projects. In our coding contests and development and mentorship programs we support new
Why adding extra text?

2020-03-28 21:38 UTC, Chaitanyassr commented on index.html
> +									<p>The 'Advanced Developer Program' is intended for developers who have previously participated successfully in an intensive FOSSASIA program such as GSoC.<div><br></div><div><br></div></p>
Why adding extra text here?

2020-03-28 21:42 UTC, Chaitanyassr commented
> On clicking, different images popup in memories section of FOSSASIA corrected
> 
> fixed: #664
> 
> preview link: https://sohan022.github.io/fossasia.org/

Is your branch is updated, if not than please make sure ones.

2020-03-29 03:52 UTC, Sohan022 commented
My branch is not updated. So, I make a new pull request.

2020-03-29 13:12 UTC, Chaitanyassr commented
> My branch is not updated. So, I make a new pull request.

just add an upstream branch and pull or merge it.

2020-09-26 10:49 UTC, closed without merging