Changed the color of links for Android Apps of Fossasia for more visibility
fossasia/fossasia.org pull request #703
Opened 2020-05-09 10:02 UTC by pruthvi2103

The color of the titles of the Android Apps of Fossasia was white and not visible, Changed the class from text-white to text-black to enhance visibility

**Before Commit:**
<img width="531" alt="Screenshot 2020-05-09 at 3 26 45 PM" src="https://user-images.githubusercontent.com/29141140/81470733-033ed880-920a-11ea-9b14-1b0c839e0fbc.png">

**After Commit:**
<img width="531" alt="Screenshot 2020-05-09 at 3 27 04 PM" src="https://user-images.githubusercontent.com/29141140/81470756-236e9780-920a-11ea-9e20-9e6f6bb9ed31.png">

2020-05-09 12:50 UTC, Chaitanyassr requested changes
Hi @pruthvi2103 great! . Can you please provide a deployed link also?

2020-05-09 13:31 UTC, pruthvi2103 commented
@Chaitanyassr sure ive dployed my branch at https://pruthvi2103.github.io/#android

2020-05-09 16:04 UTC, Chaitanyassr approved these changes
great!

2020-07-26 14:27 UTC, Raunaksingh100 approved these changes
LGTM

2020-09-28 16:40 UTC, mariobehling commented
Current implementation is sufficient.

2020-09-28 16:40 UTC, closed without merging