media query added  for   sponsorship info button
fossasia/fossasia.org pull request #738
Opened 2020-07-03 11:19 UTC by Raunaksingh100

![issue 3](https://user-images.githubusercontent.com/65535360/86464268-c47e5800-bd4c-11ea-9b12-9f8ce3d58b7f.PNG)
![issue solved](https://user-images.githubusercontent.com/65535360/86464295-cfd18380-bd4c-11ea-95cc-63a3200fdf63.PNG)

sponsorship info button collabrating with images issue fixed see in the screenshot for the better understanding

2020-07-03 11:25 UTC, Raunaksingh100 commented
this issue only need margin-bottom to give the distance ........

2020-07-03 20:35 UTC, Chaitanyassr requested changes
Hi, Please, attach a deployed link.

2020-07-04 06:54 UTC, Raunaksingh100 commented
@Chaitanyassr  can you tell where i found the deployed link because  i am new to open source contribution

2020-07-04 07:53 UTC, Raunaksingh100 commented
@Chaitanyassr  can you tell me how can i attach  deployed link because i am new to Open Source Contributions

2020-07-07 10:41 UTC, merged