Adding a comma at the end of the word knowledge
fossasia/fossasia.org pull request #768
Opened 2020-08-14 08:17 UTC by Aaishpra

I noticed there is a comma missing at the end of the word knowledge as there is a series of three words in that sentence, so a comma is necessary to separate the elements.
![image](https://user-images.githubusercontent.com/66299533/90228859-99e7ea80-de34-11ea-9a4f-128b248928b0.png)

2020-08-14 09:25 UTC, atharwa-24 approved these changes
nice Thanks

2020-08-16 14:26 UTC, Raunaksingh100 requested changes
.

2020-08-16 16:25 UTC, Raunaksingh100 approved these changes

2020-08-16 16:25 UTC, Aaishpra commented
@Raunaksingh100 as I have already mentioned that the sentence contains a series of three words that's why a comma is necessary to separate the elements.
And the example you gave contains an independent clause and a dependent clause hence we cannot use a comma to separate them.
I am attaching a screenshot of for your reference
![image](https://user-images.githubusercontent.com/66299533/90338930-cbb2aa00-e00a-11ea-94df-be4e6f830831.png)

2020-08-31 02:40 UTC, closed without merging